'use strict';

/**
 * report.js — builds a standalone, self-contained HTML report from scan findings.
 */

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const SEV_COLOR = {
  critical: '#ff2d55',
  high: '#ff6b35',
  medium: '#ffcc00',
  low: '#4cc9f0',
  info: '#7d8590',
};

function buildReport({ findings, target, grade, score, intensity }) {
  const order = { fail: 0, warn: 1, info: 2, pass: 3 };
  const sevOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  const sorted = [...findings].sort((a, b) => {
    const s = (order[a.status] ?? 9) - (order[b.status] ?? 9);
    if (s !== 0) return s;
    return (sevOrder[a.severity] ?? 9) - (sevOrder[b.severity] ?? 9);
  });

  const counts = findings.reduce((acc, f) => {
    const key = f.status === 'fail' || f.status === 'warn' ? f.severity : f.status;
    acc[key] = (acc[key] || 0) + 1;
    return acc;
  }, {});

  const rows = sorted
    .map((f) => {
      const color = SEV_COLOR[f.severity] || '#7d8590';
      const badge =
        f.status === 'pass'
          ? '<span style="color:#3ddc97">PASS</span>'
          : `<span style="color:${color}">${esc((f.severity || f.status).toUpperCase())}</span>`;
      const repro =
        (f.url ? `<div><span style="color:#59636e">URL:</span> <a href="${esc(f.url)}" style="color:#39d0d8">${esc(f.url)}</a></div>` : '') +
        (f.curl ? `<pre style="color:#3ddc97;margin:.3rem 0 0">${esc(f.curl)}</pre>` : '');
      return `<tr>
        <td>${badge}</td>
        <td><strong>${esc(f.category)}</strong><br><span style="color:#8b98a5">${esc(f.title)}</span></td>
        <td><pre>${esc(f.evidence)}</pre>${repro}</td>
        <td>${esc(f.remediation)}</td>
      </tr>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Smart Scan Report — ${esc(target)}</title>
<style>
  :root { color-scheme: dark; }
  body { font-family: ui-monospace, Menlo, Consolas, monospace; background:#0b0f14; color:#e6edf3; margin:0; padding:2rem; }
  h1 { color:#39d0d8; }
  .meta { color:#8b98a5; margin-bottom:1.5rem; }
  .grade { font-size:3rem; font-weight:bold; }
  table { width:100%; border-collapse:collapse; margin-top:1rem; }
  th, td { text-align:left; vertical-align:top; padding:.6rem .5rem; border-bottom:1px solid #1e2732; font-size:.85rem; }
  th { color:#39d0d8; position:sticky; top:0; background:#0b0f14; }
  pre { white-space:pre-wrap; word-break:break-word; margin:0; color:#b8c2cc; max-width:34ch; }
  .pill { display:inline-block; padding:.15rem .5rem; border-radius:1rem; margin-right:.4rem; font-size:.8rem; }
</style></head>
<body>
  <h1>Smart Scan Security Report</h1>
  <div class="meta">
    Target: <strong>${esc(target)}</strong><br>
    Intensity: ${esc(intensity || 'active')} &middot; Generated: ${esc(new Date().toISOString())}
  </div>
  <div class="grade" style="color:${grade === 'A' ? '#3ddc97' : grade === 'F' ? '#ff2d55' : '#ffcc00'}">
    Grade ${esc(grade || '?')} <span style="font-size:1rem;color:#8b98a5">(score ${esc(score ?? '?')}/100)</span>
  </div>
  <div style="margin:.8rem 0">
    ${Object.entries(counts)
      .map(
        ([k, v]) =>
          `<span class="pill" style="background:${SEV_COLOR[k] || '#26313d'};color:#0b0f14">${esc(k)}: ${v}</span>`
      )
      .join('')}
  </div>
  <table>
    <thead><tr><th>Severity</th><th>Finding</th><th>Evidence</th><th>Remediation</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <p style="color:#59636e;margin-top:2rem;font-size:.8rem">
    Generated by Smart Scan. For authorized security testing only.
  </p>
</body></html>`;
}

module.exports = { buildReport };
